name: enough_icalendar_export
description: Exports calendar events to the native calendar.
version: 0.4.0
homepage: https://github.com/Enough-Software/enough_icalendar_export
topics: 
 - icalendar
 - ics
 - ical
 - rfc5545
 - rfc5546

environment:
  sdk: ">=3.11.0 <4.0.0"
  flutter: ">=3.41.0"

dependencies:
  flutter:
    sdk: flutter
  add_2_calendar_plus: ^1.0.0
  enough_icalendar: #^0.17.0
      git:
        url: https://github.com/Enough-Software/enough_icalendar.git
#  path: ../enough_icalendar
    
dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter: null
